CREATE TABLE produto(id INTEGER AUTO_INCREMENT, nome TEXT, cod INTEGER UNIQUE, valor DOUBLE, qtd INTEGER, CONSTRAINT PRIMARY KEY(id))

CREATE TABLE venda(id INTEGER AUTO_INCREMENT, total TEXT, pagamento TEXT, data DATETIME DEFAULT CURRENT_DATE(), CONSTRAINT PRIMARY KEY(id))

CREATE TABLE venda_produto(cod_produto INTEGER, id_venda INTEGER, 
CONSTRAINT FOREIGN KEY(cod_produto) REFERENCES produto(cod) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY(id_venda) REFERENCES venda(id) ON DELETE CASCADE ON UPDATE CASCADE)