CREATE TABLE produto(id INTEGER AUTO_INCREMENT, nome TEXT, cod TEXT UNIQUE, valor DOUBLE, qtd INTEGER, CONSTRAINT PRIMARY KEY(id))

CREATE TABLE venda(id INTEGER AUTO_INCREMENT, total TEXT, pagamento TEXT, data DATETIME DEFAULT CURRENT_DATE(), CONSTRAINT PRIMARY KEY(id))

CREATE TABLE venda_produto(id_produto INTEGER, id_venda INTEGER, 
CONSTRAINT FOREIGN KEY(id_produto) REFERENCES produto(id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY(id_venda) REFERENCES venda(id) ON DELETE CASCADE ON UPDATE CASCADE
                          )